# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62dc2325a241dedd152468bb4d39c8e6eebc0fa6f1e51512cf00d0f2265a88eee1c10a4387a53176a549b630a95b596983ac928ff5eb3fdb707fb67d643b51ac

test:
  secret_key_base: 010104bb942f42eb18dd29fe6897fa56e30b8d328380a6d079a589a5963e1c8ca534d712de9e5346d8b7b0f17550d1f1b88081283f96f3b4120c1f0523fd7405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
